spring.application.name=misr_shoryan_elataa
server.port=9090
# Datasource (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MisrShoryanElAtaa;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=springBootUser
spring.datasource.password=StrongPassword@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# # Fix for JSR-310 converters (Hibernate 6 compatibility)
# spring.data.jpa.repositories.enabled-context-converters=false


spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=misrshoryanelataa@gmail.com
spring.mail.password=waid thog jxkd fsdx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true


