spring.application.name=misr_shoryan_elataa
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/MisrShoryanElAtaa?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# # Fix for JSR-310 converters (Hibernate 6 compatibility)
# spring.data.jpa.repositories.enabled-context-converters=false


spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=misrshoryanelataa@gmail.com
spring.mail.password=waid thog jxkd fsdx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true


